version: '3.7'
services:
  web:
    build: ./services/web
    command: gunicorn --log-level info --log-file=/log/netvaders_gunicorn.log --workers 4 --bind 0.0.0.0:5000 project:app
    volumes:
      - ./services/web/project/static:/app/project/static
      - ./services/web/project/log:/app/project/log
      - ./services/web/project/templates:/app/project/templates
    depends_on:
      - postgres
    expose:
      - 5000
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      snet:

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    environment:
      TZ: 'Europe/Budapest'
      PGTZ: 'Europe/Budapest'
    volumes:
        - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      snet:
      
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/web/project/static:/app/project/static
    ports:
      # - 1334:80
      - 1334:443
    depends_on:
      - web
    restart: unless-stopped
    networks:
      snet:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin


networks:
  snet:

volumes:
  postgres:
  static:
  logs:
  pgadmin-data:
